---
apiVersion: v1
kind: Namespace
metadata:
  name: random-statsd-client
spec: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: random-statsd-client
  namespace: random-statsd-client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-statsd-client
  namespace: random-statsd-client
spec:
  replicas: 1
  selector:
    matchLabels:
      name: random-statsd-client
  template:
    metadata:
      labels:
        name: random-statsd-client
    spec:
      serviceAccountName: random-statsd-client
      containers:
        - name: random-statsd-client
          image: quay.io/nmalik/random-statsd-client:latest
          imagePullPolicy: Always
